package VistaAlmacen;

public class VistaAlmacenCosecha extends javax.swing.JFrame {

    /**
     * Creates new form VistaAlmacenCosecha
     */
    public VistaAlmacenCosecha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCosecha = new javax.swing.JPanel();
        ListarForraje = new javax.swing.JButton();
        ListarCosecha = new javax.swing.JButton();
        PanelListaCosecha = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelCosecha.setBackground(new java.awt.Color(255, 255, 255));
        PanelCosecha.setMaximumSize(new java.awt.Dimension(710, 466));
        PanelCosecha.setMinimumSize(new java.awt.Dimension(710, 466));
        PanelCosecha.setPreferredSize(new java.awt.Dimension(710, 466));

        ListarForraje.setBackground(new java.awt.Color(0, 102, 102));
        ListarForraje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ListarForraje.setForeground(new java.awt.Color(255, 255, 255));
        ListarForraje.setText("LISTAR FORRAJE");
        ListarForraje.setPreferredSize(new java.awt.Dimension(140, 25));

        ListarCosecha.setBackground(new java.awt.Color(0, 102, 102));
        ListarCosecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ListarCosecha.setForeground(new java.awt.Color(255, 255, 255));
        ListarCosecha.setText("LISTAR COSECHA");
        ListarCosecha.setPreferredSize(new java.awt.Dimension(140, 25));

        PanelListaCosecha.setBackground(new java.awt.Color(0, 102, 102));
        PanelListaCosecha.setPreferredSize(new java.awt.Dimension(698, 398));

        javax.swing.GroupLayout PanelListaCosechaLayout = new javax.swing.GroupLayout(PanelListaCosecha);
        PanelListaCosecha.setLayout(PanelListaCosechaLayout);
        PanelListaCosechaLayout.setHorizontalGroup(
            PanelListaCosechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelListaCosechaLayout.setVerticalGroup(
            PanelListaCosechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelCosechaLayout = new javax.swing.GroupLayout(PanelCosecha);
        PanelCosecha.setLayout(PanelCosechaLayout);
        PanelCosechaLayout.setHorizontalGroup(
            PanelCosechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCosechaLayout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addComponent(ListarForraje, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addComponent(ListarCosecha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(PanelCosechaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelListaCosecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelCosechaLayout.setVerticalGroup(
            PanelCosechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCosechaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PanelCosechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListarForraje, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListarCosecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelListaCosecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelCosecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelCosecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ListarCosecha;
    public javax.swing.JButton ListarForraje;
    public javax.swing.JPanel PanelCosecha;
    public javax.swing.JPanel PanelListaCosecha;
    // End of variables declaration//GEN-END:variables
}
