
package VistaPaneles;

public class GestionAlmacen extends javax.swing.JFrame {

    /**
     * Creates new form GestionAlmacen
     */
    public GestionAlmacen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGestionAlmacen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AlmacenCosecha = new javax.swing.JButton();
        AlmacenGanado = new javax.swing.JButton();
        PanelAlmacen = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelGestionAlmacen.setBackground(new java.awt.Color(102, 0, 51));
        PanelGestionAlmacen.setPreferredSize(new java.awt.Dimension(750, 650));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTION ALMACEN");
        jLabel1.setPreferredSize(new java.awt.Dimension(210, 45));

        AlmacenCosecha.setBackground(new java.awt.Color(0, 102, 102));
        AlmacenCosecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AlmacenCosecha.setForeground(new java.awt.Color(255, 255, 255));
        AlmacenCosecha.setText("ALMACEN COSECHA");
        AlmacenCosecha.setPreferredSize(new java.awt.Dimension(180, 30));
        AlmacenCosecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlmacenCosechaActionPerformed(evt);
            }
        });

        AlmacenGanado.setBackground(new java.awt.Color(0, 102, 102));
        AlmacenGanado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AlmacenGanado.setForeground(new java.awt.Color(255, 255, 255));
        AlmacenGanado.setText("ALMACEN GANADO");
        AlmacenGanado.setPreferredSize(new java.awt.Dimension(180, 30));
        AlmacenGanado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlmacenGanadoActionPerformed(evt);
            }
        });

        PanelAlmacen.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout PanelAlmacenLayout = new javax.swing.GroupLayout(PanelAlmacen);
        PanelAlmacen.setLayout(PanelAlmacenLayout);
        PanelAlmacenLayout.setHorizontalGroup(
            PanelAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        PanelAlmacenLayout.setVerticalGroup(
            PanelAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageneIcon/IconoAlmacen.png"))); // NOI18N

        javax.swing.GroupLayout PanelGestionAlmacenLayout = new javax.swing.GroupLayout(PanelGestionAlmacen);
        PanelGestionAlmacen.setLayout(PanelGestionAlmacenLayout);
        PanelGestionAlmacenLayout.setHorizontalGroup(
            PanelGestionAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGestionAlmacenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AlmacenCosecha, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(AlmacenGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
            .addGroup(PanelGestionAlmacenLayout.createSequentialGroup()
                .addGroup(PanelGestionAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGestionAlmacenLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelGestionAlmacenLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(PanelAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        PanelGestionAlmacenLayout.setVerticalGroup(
            PanelGestionAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGestionAlmacenLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PanelGestionAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelGestionAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGestionAlmacenLayout.createSequentialGroup()
                        .addGap(18, 89, Short.MAX_VALUE)
                        .addComponent(PanelAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(PanelGestionAlmacenLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(PanelGestionAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AlmacenGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AlmacenCosecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelGestionAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelGestionAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AlmacenCosechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlmacenCosechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlmacenCosechaActionPerformed

    private void AlmacenGanadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlmacenGanadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlmacenGanadoActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AlmacenCosecha;
    public javax.swing.JButton AlmacenGanado;
    public javax.swing.JPanel PanelAlmacen;
    public javax.swing.JPanel PanelGestionAlmacen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
