
package VistaPaneles;

public class GestionTerreno extends javax.swing.JFrame {

    /**
     * Creates new form GestionTerreno
     */
    public GestionTerreno() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTerreno = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ListarTerreno = new javax.swing.JButton();
        Cronograma = new javax.swing.JButton();
        PanelGestion = new javax.swing.JPanel();
        Produccion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelTerreno.setBackground(new java.awt.Color(102, 0, 51));
        PanelTerreno.setPreferredSize(new java.awt.Dimension(750, 650));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTION TERRENO");

        ListarTerreno.setBackground(new java.awt.Color(0, 102, 102));
        ListarTerreno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ListarTerreno.setForeground(new java.awt.Color(255, 255, 255));
        ListarTerreno.setText("Listar Terreno");
        ListarTerreno.setPreferredSize(new java.awt.Dimension(150, 30));
        ListarTerreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarTerrenoActionPerformed(evt);
            }
        });

        Cronograma.setBackground(new java.awt.Color(0, 102, 102));
        Cronograma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cronograma.setForeground(new java.awt.Color(255, 255, 255));
        Cronograma.setText("Cronograma de Trabajo");
        Cronograma.setPreferredSize(new java.awt.Dimension(210, 30));
        Cronograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CronogramaActionPerformed(evt);
            }
        });

        PanelGestion.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout PanelGestionLayout = new javax.swing.GroupLayout(PanelGestion);
        PanelGestion.setLayout(PanelGestionLayout);
        PanelGestionLayout.setHorizontalGroup(
            PanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        PanelGestionLayout.setVerticalGroup(
            PanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        Produccion.setBackground(new java.awt.Color(0, 102, 102));
        Produccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Produccion.setForeground(new java.awt.Color(255, 255, 255));
        Produccion.setText("Produccion");
        Produccion.setPreferredSize(new java.awt.Dimension(150, 30));
        Produccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProduccionActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageneIcon/IconoTerreno.png"))); // NOI18N

        javax.swing.GroupLayout PanelTerrenoLayout = new javax.swing.GroupLayout(PanelTerreno);
        PanelTerreno.setLayout(PanelTerrenoLayout);
        PanelTerrenoLayout.setHorizontalGroup(
            PanelTerrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTerrenoLayout.createSequentialGroup()
                .addGroup(PanelTerrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTerrenoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelTerrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelTerrenoLayout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(ListarTerreno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cronograma, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(65, 65, 65)
                            .addComponent(Produccion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelTerrenoLayout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(PanelGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        PanelTerrenoLayout.setVerticalGroup(
            PanelTerrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTerrenoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelTerrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(PanelTerrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListarTerreno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cronograma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Produccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(PanelGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelTerreno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelTerreno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListarTerrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarTerrenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListarTerrenoActionPerformed

    private void CronogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CronogramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CronogramaActionPerformed

    private void ProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProduccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProduccionActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Cronograma;
    public javax.swing.JButton ListarTerreno;
    public javax.swing.JPanel PanelGestion;
    public javax.swing.JPanel PanelTerreno;
    public javax.swing.JButton Produccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
