
package VistaPaneles;

public class GestionGanado extends javax.swing.JFrame {

    /**
     * Creates new form GestionGanado
     */
    public GestionGanado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGestionGanado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RegistroGanado = new javax.swing.JButton();
        ListarGanado = new javax.swing.JButton();
        PanelGanado = new javax.swing.JPanel();
        ProduccionGanado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelGestionGanado.setBackground(new java.awt.Color(102, 0, 51));
        PanelGestionGanado.setPreferredSize(new java.awt.Dimension(750, 650));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTION GANADO");
        jLabel1.setPreferredSize(new java.awt.Dimension(250, 30));

        RegistroGanado.setBackground(new java.awt.Color(0, 102, 102));
        RegistroGanado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RegistroGanado.setForeground(new java.awt.Color(255, 255, 255));
        RegistroGanado.setText("REGISTRO GANADO");
        RegistroGanado.setPreferredSize(new java.awt.Dimension(200, 34));
        RegistroGanado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroGanadoActionPerformed(evt);
            }
        });

        ListarGanado.setBackground(new java.awt.Color(0, 102, 102));
        ListarGanado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ListarGanado.setForeground(new java.awt.Color(255, 255, 255));
        ListarGanado.setText("LISTAR GANADO");
        ListarGanado.setPreferredSize(new java.awt.Dimension(165, 34));
        ListarGanado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarGanadoActionPerformed(evt);
            }
        });

        PanelGanado.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout PanelGanadoLayout = new javax.swing.GroupLayout(PanelGanado);
        PanelGanado.setLayout(PanelGanadoLayout);
        PanelGanadoLayout.setHorizontalGroup(
            PanelGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        PanelGanadoLayout.setVerticalGroup(
            PanelGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        ProduccionGanado.setBackground(new java.awt.Color(0, 102, 102));
        ProduccionGanado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProduccionGanado.setForeground(new java.awt.Color(255, 255, 255));
        ProduccionGanado.setText("PRODUCCION GANADO");
        ProduccionGanado.setPreferredSize(new java.awt.Dimension(210, 30));
        ProduccionGanado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProduccionGanadoActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageneIcon/IconoGanado.png"))); // NOI18N

        javax.swing.GroupLayout PanelGestionGanadoLayout = new javax.swing.GroupLayout(PanelGestionGanado);
        PanelGestionGanado.setLayout(PanelGestionGanadoLayout);
        PanelGestionGanadoLayout.setHorizontalGroup(
            PanelGestionGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGestionGanadoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelGestionGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelGestionGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelGestionGanadoLayout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(PanelGanado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelGestionGanadoLayout.createSequentialGroup()
                        .addComponent(RegistroGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(ListarGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(ProduccionGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        PanelGestionGanadoLayout.setVerticalGroup(
            PanelGestionGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGestionGanadoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PanelGestionGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(PanelGestionGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistroGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListarGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProduccionGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(PanelGanado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelGestionGanado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelGestionGanado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistroGanadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroGanadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroGanadoActionPerformed

    private void ListarGanadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarGanadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListarGanadoActionPerformed

    private void ProduccionGanadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProduccionGanadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProduccionGanadoActionPerformed

    /**
     * @param args the command line arguments
     */  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ListarGanado;
    public javax.swing.JPanel PanelGanado;
    public javax.swing.JPanel PanelGestionGanado;
    public javax.swing.JButton ProduccionGanado;
    public javax.swing.JButton RegistroGanado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
