package Aplicacion;

import DTO.ProductoGanadoDTO;
import JDBC.ProductoGanadoJDBC;
import MySql.Conexion;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

public class Prueba extends javax.swing.JFrame {
    ProductoGanadoJDBC todoProducto;
    List<ProductoGanadoDTO> listaProducto;
    DefaultCategoryDataset barras;
    
    ArrayList<Integer> data = new ArrayList<>();
    /**
     * Creates new form Prueba
     */
    public Prueba() {
        initComponents();
        Graficar();
    }
    
    public void Graficar(){
        Connection conexion = null;
        
        try{
        conexion = Conexion.getConnection();
        if(conexion.getAutoCommit()){
            conexion.setAutoCommit(false);
        }
        todoProducto = new ProductoGanadoJDBC();
        listaProducto = todoProducto.seleccionar();
        
        conexion.commit();
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
            System.out.println("Sucedio un error al rollback");
            try {
                conexion.rollback();
            } catch (SQLException exx) {
                exx.printStackTrace(System.out);
            }
        }
        int i=1;
         barras = new DefaultCategoryDataset();
        for (ProductoGanadoDTO lista : listaProducto) {
//            data.add(lista.getIdproduccionGanado());
                double decimal = Double.parseDouble(lista.getGanancia());
                int numero = (int)decimal;
            barras.addValue( numero, lista.getProducto(), lista.getMes());
        }
//        for (int j = 0; j < data.size(); j++) {
//            barras.addValue(data.get(i) , "Peso ["+(i+1)+"]", "Vaca ["+(i+1)+"]");
//            
//        }
        
        
        
//        for (int i = 0; i < 10; i++) {
//            barras.addValue(i, "Producto", "Mes");            
//        }
        JFreeChart grafico = ChartFactory.createBarChart(
                                    "TABLA DE GANCIAS POR PRODUCTO",//nombre de la grafica
                                    "Meses",//nombre de las barras columnas
                                    "Montos de Ganancia",//nombre de la numeración
                                    barras,//datos de la grafica
                                    PlotOrientation.VERTICAL,//orientacion de la grafica
                                    false,//leyenda de barras individuales
                                    true, //herramientas
                                    false// url de la grafica
                );
        ChartPanel panel = new ChartPanel(grafico);
                            panel.setMouseWheelEnabled(true);
                            panel.setPreferredSize(new Dimension(200, 150));
                            //Designamos medinate los objetos donde se mostrara la grafica
                            jPanel1.setLayout(new BorderLayout());
                            jPanel1.add(panel, BorderLayout.NORTH);
                            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
